# Generated by Django 5.1.5 on 2025-02-02 07:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='English question')),
                ('answer', ckeditor.fields.RichTextField(help_text='English answer')),
                ('question_hi', models.TextField(blank=True, help_text='Hindi translation of question', null=True)),
                ('answer_hi', ckeditor.fields.RichTextField(blank=True, help_text='Hindi translation of answer', null=True)),
                ('question_bn', models.TextField(blank=True, help_text='Bengali translation of question', null=True)),
                ('answer_bn', models.TextField(blank=True, help_text='Bengali translation of answer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
